### Authentication API Tests


### Base URL

@host = http://localhost:8080/api


### 


### Register a new user

# @name register

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "confirmPassword": "28935617Aa@",
  "email": "kratos@gmail.com",
  "password": "28935617Aa@",
  "username": "Kratos"
}


### 


### Login and capture token

# @name login

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "robertarussel17@yahoo.com",
  "password": "password123"
}

> {%
  var token = response.body.data.token;
  client.global.set("userAuth", "Bearer " + token);
%}


### 


### Validate token

GET {{host}}/auth/validate HTTP/1.1
Authorization: {{userAuth}}
