### Authentication API Tests


### Base URL

@host = http://localhost:8080/api


### Register a new user

# @name register

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "avatarUrl": "https://avatars.githubusercontent.com/u/10137?v=4",
  "confirmPassword": "28935617Aa@",
  "email": "kratosgado@gmail.com",
  "password": "28935617Aa@",
  "username": "Kratos"
}


### Login and capture token

# @name login

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "kratosgado@gmail.com",
  "password": "28935617Aa@"
}

> {%
  var token = response.body.data.token;
  client.global.set("userAuth", "Bearer " + token);
%}


### Validate token

GET {{host}}/auth/validate HTTP/1.1
Authorization: {{userAuth}}
