### Comments API Tests


### Base URL

@host = http://localhost:8080/api


### Login first to get token

# @name login

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "kratos@gmail.com",
  "password": "28935617Aa@"
}


### 


### Create a new comment

# @name createComment

POST {{host}}/comments HTTP/1.1
Content-Type: application/json
Authorization: {{adminAuth}}

{
  "content": "Great article! Very helpful information about Spring Boot 3.",
  "postId": 1
}


### 


### Create a reply to a comment

# @name createReply

POST {{host}}/comments HTTP/1.1
Content-Type: application/json
Authorization: {{adminAuth}}

{
  "content": "I agree! This is really helpful.",
  "parentId": 1,
  "postId": 1
}


### 


### Update a comment

# @name updateComment

PUT {{host}}/comments/1 HTTP/1.1
Content-Type: application/json
Authorization: {{adminAuth}}

{
  "content": "Great article! Very helpful and comprehensive information about Spring Boot 3."
}


### 


### Get a single comment by ID

# @name getComment

GET {{host}}/comments/1 HTTP/1.1
Authorization: {{adminAuth}}


### 


### Get comments by post

# @name getPostComments

GET {{host}}/comments/post/1?page=0&size=10 HTTP/1.1


### 


### Get comments with pagination - Second page

# @name getCommentsPage2

GET {{host}}/comments/post/1?page=1&size=5 HTTP/1.1


### 


### Delete a comment

# @name deleteComment

DELETE {{host}}/comments/1 HTTP/1.1
Authorization: {{adminAuth}}


### 


### Test create comment with empty content (validation)

# @name createInvalidComment

POST {{host}}/comments HTTP/1.1
Content-Type: application/json
Authorization: {{adminAuth}}

{
  "content": "",
  "postId": 1
}


### 


### Test create comment for non-existent post

# @name createCommentInvalidPost

POST {{host}}/comments HTTP/1.1
Content-Type: application/json
Authorization: {{adminAuth}}

{
  "content": "This should fail",
  "postId": 99999
}


### 


### Test create comment without authentication (should fail)

# @name createCommentUnauthorized

POST {{host}}/comments HTTP/1.1
Content-Type: application/json

{
  "content": "This should fail - no auth token",
  "postId": 1
}


### 


### Approve a comment (Admin only)

# @name approveComment

PUT {{host}}/comments/1/approve HTTP/1.1
Authorization: {{adminAuth}}


### 


### Reject a comment (Admin only)

# @name rejectComment

PUT {{host}}/comments/1/reject HTTP/1.1
Authorization: {{adminAuth}}


### 
