### Posts V2 API Tests (Optimized)


### Base URL

@host = http://localhost:8080/api/v2


### Search posts (Optimized FTS)

# @name searchPosts

GET {{host}}/posts/search?keyword=booting&page=0&size=10 HTTP/1.1


### Get trending posts

# @name getTrendingPosts

GET {{host}}/posts/trending HTTP/1.1


### Get posts by category (Optimized)

# @name getCategoryPostsOptimized

GET {{host}}/posts/category/1/optimized HTTP/1.1


### Get posts by tag (Optimized)

# @name getTagPostsOptimized

GET {{host}}/posts/tag/1/optimized HTTP/1.1
