### Users API Tests


### Base URL

@host = http://localhost:8080/api


### Get all users (Admin only, with pagination)

# @name getAllUsers

GET {{host}}/users?page=1&size=10 HTTP/1.1
Authorization: {{userAuth}}

> {%
  const body = response.body.data.content;
  client.global.set("userId", body[4].id);
%}


### Get user by ID

# @name getUser

GET {{host}}/users/{{userId}} HTTP/1.1


### Update user profile

# @name updateProfile

PUT {{host}}/users/{{userId}}/profile HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "avatarUrl": "https://example.com/avatar.jpg",
  "bio": "Full-stack developer passionate about Spring Boot and React",
  "location": "San Francisco, CA",
  "website": "https://example.com"
}


### Change password

# @name changePassword

PUT {{host}}/users/{{userId}}/password HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "confirmPassword": "newPassword456!",
  "newPassword": "newPassword456!",
  "oldPassword": "oldPassword123"
}


### Update avatar

# @name updateAvatar

PUT {{host}}/users/9/avatar HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "avatarUrl": "https://example.com/new-avatar.jpg"
}


### Get user's posts

# @name getUserPosts

GET {{host}}/users/1/posts?page=0&size=10 HTTP/1.1
Authorization: {{userAuth}}


### Get user's comments

# @name getUserComments

GET {{host}}/users/1/comments?page=0&size=10 HTTP/1.1
Authorization: {{userAuth}}


### Delete user account (should be restricted)

# @name deleteUser

DELETE {{host}}/users/1 HTTP/1.1
Authorization: {{userAuth}}


### Search users by username

# @name searchUsers

GET {{host}}/users/search?q=john&page=0&size=10 HTTP/1.1
Authorization: {{userAuth}}


### Test update profile with invalid data

# @name updateInvalidProfile

PUT {{host}}/users/1/profile HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "bio": "",
  "location": "",
  "website": "not-a-valid-url"
}


### Test unauthorized profile update

# @name updateProfileUnauthorized

PUT {{host}}/users/1/profile HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "bio": "Trying to update someone else's profile"
}


### Test password change with wrong current password

# @name changePasswordWrong

PUT {{host}}/users/1/password HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "confirmPassword": "newPassword456!",
  "currentPassword": "wrongPassword",
  "newPassword": "newPassword456!"
}


### Test password change with mismatched confirmation

# @name changePasswordMismatch

PUT {{host}}/users/1/password HTTP/1.1
Content-Type: application/json
Authorization: {{userAuth}}

{
  "confirmPassword": "differentPassword!",
  "currentPassword": "oldPassword123",
  "newPassword": "newPassword456!"
}


### Get user statistics

# @name getUserStats

GET {{host}}/users/1/stats HTTP/1.1
