server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Blog Backend

  data:
    rest:
      base-path: /data
      default-page-size: 10
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true
      detection-strategy: annotated # or 'default' to expose all repositories
    hateoas:
      use-hal-as-default-json-media-type: false
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_NAME}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            # redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

cors:
  allowed-origins: http://localhost:8080,http://localhost:3000,http://localhost:4200,https://studio.apollographql.com

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 5
      limitRefreshPeriod: 10s
      timeoutDuration: 0

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html
    enabled: true
  # show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
